In [40]:
import numpy as np

import pandas
from pandas.plotting import scatter_matrix
import matplotlib.pyplot as plt
from sklearn import model_selection
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC

In [41]:
dataset=pd.read_csv("train.csv").as_matrix()

In [42]:
# shape
print(dataset.shape)

(100, 2)


In [43]:
array = dataset
X = array[:,0:2]
Y = array[:,1]
validation_size = 0.20
seed = 7
X_train, X_validation, Y_train, Y_validation = model_selection.train_test_split(X, Y, test_size=validation_size, random_state=seed)

In [44]:
knn = KNeighborsClassifier()
knn.fit(X_train, Y_train)
predictions = knn.predict(X_validation)
print(accuracy_score(Y_validation, predictions))
print(confusion_matrix(Y_validation, predictions))
print(classification_report(Y_validation, predictions))

0.55
[[3 0 3 0]
 [0 1 0 0]
 [1 1 5 1]
 [0 0 3 2]]
             precision    recall  f1-score   support

          1       0.75      0.50      0.60         6
          2       0.50      1.00      0.67         1
          3       0.45      0.62      0.53         8
          4       0.67      0.40      0.50         5

avg / total       0.60      0.55      0.55        20

